import time

class PRService:
    def __init__(self, github_service, ai_service):
        self.github_service = github_service
        self.ai_service = ai_service
    
    def process_issue(self, repo_full_name, issue_number, issue_title, issue_body, comment_body):
        try:
            repo = self.github_service.get_repository(repo_full_name)
        except ValueError as e:
            return {
                'success': False,
                'message': str(e)
            }
        
        codebase_files = self.github_service.get_relevant_files(repo, max_files=15)
        
        if not codebase_files:
            return {
                'success': False,
                'message': 'Could not fetch codebase files'
            }
        
        ai_result = self.ai_service.analyze_issue_and_plan_changes(
            issue_title=issue_title,
            issue_body=issue_body,
            comment_body=comment_body,
            codebase_files=codebase_files
        )
        
        file_changes = ai_result.get('file_changes', [])
        
        if not file_changes:
            return {
                'success': False,
                'message': 'AI did not suggest any file changes',
                'analysis': ai_result.get('analysis')
            }
        
        branch_name = f"ai-fix-issue-{issue_number}-{int(time.time())}"
        branch_created = self.github_service.create_branch(repo, branch_name)
        
        if not branch_created:
            return {
                'success': False,
                'message': 'Failed to create branch'
            }
        
        changes_applied = []
        for change in file_changes:
            file_path = change['file_path']
            new_content = change['new_content']
            reason = change['reason']
            
            success = self.github_service.update_file(
                repo=repo,
                file_path=file_path,
                content=new_content,
                message=f"AI: {reason}",
                branch=branch_name
            )
            
            if success:
                changes_applied.append({
                    'file': file_path,
                    'reason': reason
                })
        
        if not changes_applied:
            return {
                'success': False,
                'message': 'Failed to apply any changes'
            }
        
        pr_title = f"AI Fix: {issue_title}"
        pr_body = f"""This PR was automatically generated in response to issue #{issue_number}.

## Changes Made:
{chr(10).join([f"- **{change['file']}**: {change['reason']}" for change in changes_applied])}

## AI Analysis:
{ai_result.get('analysis')}

---
Generated by @my-tool AI automation"""
        
        pr_result = self.github_service.create_pull_request(
            repo=repo,
            title=pr_title,
            body=pr_body,
            head_branch=branch_name
        )
        
        return {
            'success': pr_result.get('success'),
            'pr_url': pr_result.get('pr_url'),
            'pr_number': pr_result.get('pr_number'),
            'changes_applied': changes_applied,
            'branch': branch_name
        }
